/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fcf2eb",
        "surface-container": "#f6ece6",
        "surface-container-high": "#f0e6e0",
        "surface-container-highest": "#eae1da",
        "surface": "#fff8f5",
        "surface-bright": "#fff8f5",
        "surface-dim": "#e2d8d2",
        "surface-variant": "#eae1da",
        "on-surface": "#1f1b17",
        "on-surface-variant": "#564339",
        "inverse-surface": "#342f2b",
        "inverse-on-surface": "#f9efe8",
        "outline": "#897267",
        "outline-variant": "#ddc1b3",
        "surface-tint": "#9c4400",
        "primary": "#984300",
        "primary-container": "#ba5814",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbca",
        "primary-fixed-dim": "#ffb68e",
        "on-primary-fixed": "#331200",
        "on-primary-fixed-variant": "#773300",
        "secondary": "#5a6240",
        "secondary-container": "#dce4b9",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5e6644",
        "secondary-fixed": "#dee7bc",
        "secondary-fixed-dim": "#c2cba1",
        "on-secondary-fixed": "#181e04",
        "on-secondary-fixed-variant": "#424a2a",
        "tertiary": "#8d4b00",
        "tertiary-container": "#b15f00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6e3900",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "background": "#fff8f5",
        "on-background": "#1f1b17"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1.5rem",
        "gutter-mobile": "0.75rem",
        margin: "2.5rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "telemetry-num": ["Inter", "monospace"]
      }
    }
  },
  plugins: [],
}
